name: "Remove Glob Pattern from Git History"
description: "Remove a glob pattern from Git history across all commits."
inputs:
  glob_pattern:
    description: "Glob pattern to remove from the Git history."
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch the full history to allow rewriting

    - name: Install git-filter-repo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global advice.detachedHead false
        git clone --depth 1 --branch v2.34.0 https://github.com/newren/git-filter-repo.git
        cd git-filter-repo
        sudo cp -a git-filter-repo $(git --exec-path)
        cd ..

    - name: Clone Clean State
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone "https://github.com/${GITHUB_REPOSITORY}.git" clone
        cd clone
        git switch -C "${GITHUB_REF_NAME}"

    - name: Remove Glob Pattern from History
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Before:"
        du -sh .git

        git filter-repo --invert-paths --path-glob "${{ github.event.inputs.glob_pattern }}" --force
        git for-each-ref --format="delete %(refname)" refs/original | git update-ref --stdin
        git reflog expire --expire=now --all
        git gc --prune=now

        echo "After:"
        du -sh .git

    - name: Force Push Rewritten History
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push --force --all
        git push --force --tags
