name: "Remove Glob Pattern from Git History"
description: "Remove a glob pattern from Git history across all commits."
inputs:
  glob_pattern:
    description: "Glob pattern to remove from the Git history."
    required: true
  github_token:
    description: "GitHub token to use for the action."
    required: true
  ref_name:
    description: "Git ref name to use for the action."
    required: true
  repository:
    description: "GitHub repository to use for the action."
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch the full history to allow rewriting

    - name: Install git-filter-repo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git config --global advice.detachedHead false
        git clone --depth 1 --branch v2.34.0 https://github.com/newren/git-filter-repo.git
        cd git-filter-repo
        sudo cp -a git-filter-repo $(git --exec-path)
        cd ..

    - name: Clone Clean State
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git clone "https://github.com/${{ inputs.repository }}.git" clone
        cd clone
        git switch -C "${{ inputs.ref_name }}"

    - name: Remove Glob Pattern from History
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git branch --set-upstream-to=origin/${{ inputs.ref_name }} ${{ inputs.ref_name }}
        git pull --rebase

        echo "Before:"
        du -sh .git

        git filter-repo --invert-paths --path-glob "${{ inputs.glob_pattern }}" --force
        git for-each-ref --format="delete %(refname)" refs/original | git update-ref --stdin
        git reflog expire --expire=now --all
        git gc --prune=now

        echo "After:"
        du -sh .git

    - name: Force Push Rewritten History
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ inputs.repository }}
        git push origin --all --force
        git push origin --tags --force
