name: Update MaxMind Databases

on:
  schedule:
    - cron: "34 1 * * *" # Runs at 1:34am UTC every day (34, just so it doesn't run at the same time as the other workflows)
  workflow_dispatch:

jobs:
  update-maxmind-databases:
    name: Update MaxMind Databases
    runs-on: ubuntu-latest
    if: github.repository == 'ip-lookup/redistribution'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: ./scripts/ci-cron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
